### ISSUE TITLE
clustermap

### ISSUE THREAD

**Issue by wangjiawen2013** [kamicollo/idendrogram#14]
Hi,
Does idendrogram support clustermap like in (https://seaborn.pydata.org/generated/seaborn.clustermap.html) ?

**Comment by kamicollo** [comment]
No, it does not. It's an interesting type of chart, but I'm not sure if the plotting backends (Altair or Plotly) could even produce such a chart. In `idendrogram`, the closest you can get is by working with custom tooltips (especially in D3), where you could get them to include any attributes of interest.
